# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DateRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surename', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('priceDays', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=50)),
                ('numberCard', models.IntegerField()),
                ('maxGuest', models.IntegerField()),
                ('comision', models.DecimalField(decimal_places=2, max_digits=3)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospedajes.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospedajes.Guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospedajes.Property')),
            ],
        ),
        migrations.AddField(
            model_name='daterental',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospedajes.Property'),
        ),
        migrations.AddField(
            model_name='daterental',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospedajes.Reservation'),
        ),
    ]
