# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospedajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='dateRental',
        ),
        migrations.AddField(
            model_name='daterental',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospedajes.Reservation'),
        ),
    ]
