# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospedajes', '0002_auto_20171110_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
